<h1 style="text-align:center">Deep Learning  Lab Session </h1>
<h1 style="text-align:center">First Lab Session - 3 Hours </h1>
<h1 style="text-align:center">Artificial Neural Networks for Handwritten Digits Recognition</h1>

<b> Student 1:</b> Benedetto Luca  
<b> Student 2:</b> Ibarrondo Alberto
 
 
The aim of this session is to practice with Artificial Neural Networks. Answers and experiments should be made by groups of one or two students. Each group should fill and run appropriate notebook cells. 

To generate your final report, use print as PDF (Ctrl+P). Do not forget to run all your cells before generating your final report and do not forget to include the names of all participants in the group. The lab session should be completed by April 7th 2017. 

# Introduction


In this session, your will implement, train and test a Neural Network
for the Handwritten Digits Recognition problem <a href="http://yann.lecun.com/exdb/mnist/"> [1] </a> with  different settings of hyper parameters. You will use the MNIST dataset which was constructed from a number of scanned document dataset available from the National Institute of Standards and Technology (NIST). Images of digits were taken from a variety of scanned documents, normalized in size and centered. 


<img src="Nimages/mnist.png",width="350" height="500" align="center">
<center><span>Figure 1: MNIST digits examples</span></center>


This assignment includes a written part of programms to help you understand how to build and train
your neural net and then to test your code and get restults. 

1. <a href="NeuralNetwork.py"> NeuralNetwork.py </a> 
2. <a href="transfer_functions.py"> transfer_functions.py </a> 
3.  <a href="utils.py "> utils.py </a> 


Functions defined inside the python files mentionned above can be imported  using the python command : 
from filename import *

You will use the following libraries:

1. <a href="http://cs231n.github.io/python-numpy-tutorial/"> numpy </a>: for creating arrays and using methods to manipulate arrays.

2. <a href="http://matplotlib.org/"> matplotlib  </a>: for making plots
 








# Section 1 :  My First Neural Network

<b>Part 1</b>: Before designing and writing your code, you will first work on a neural network by hand. 
Consider the above Neural network with two inputs $X=(x1,x2)$, one hidden layers and a single output unit $(y)$.
The initial weights are set to random values. Neurons 6 and 7 represent the bias. Bias values are equal to 1.  
Training sample, X = (0.8, 0.2), whose class label is Y=0.4.

Assume that the neurons have a Sigmoid activation function  $f(x)=\frac{1}{(1+e^{-x})}$ and the learning rate $\mu$=1


<img src="Nimages/NN.png", width="700" height="900"> 
<center><span>Figure 2: Neural network </span></center>


<b>Question 1.1.1</b>: Compute the new values of weights $w_{i,j}$ after a forward pass and a backward pass.
$w_{i,j}$ is the weight of the connexion between neuron $i$ and neuron $j$.

In [1]:
import numpy as np
import matplotlib as plt
import Resources.NNet as nn
import Resources.transfer_functions as tf

In [75]:
# Calculating manually all the values (printing has been supressed)
# Initial values
x = np.array([0.8, 0.2, 1])
w1 = np.array([[0.3, -0.5], [0.8, 0.2], [0.2, -0.4]])
w2 = np.array([-0.6, 0.4, 0.5])
y = np.array(0.4)
u = np.array(1)

#Feedforward computation
u1 = np.append(np.dot(x, w1), 1.0)
o1 = tf.sigmoid(u1)

u2 = np.dot(o1, w2)
o2 = tf.sigmoid(u2)


#Backward computation
E = (1.0/2.0)*((y-o2)**2.0)

dEdu2 = (y-o2)*tf.dsigmoid(o2)
dEdu1 = w2.dot(dEdu2)*tf.dsigmoid(o1)

w2 += u*np.outer(dEdu2,o1)
w1 += u*np.outer(x,dEdu1[:-1])

print('dEdu2: ', dEdu2)
print('dEdu1: ', dEdu1)
print('x: ', x)
print('w2 : ', w2)
print('w1: ', w1)

ValueError: non-broadcastable output operand with shape (3,) doesn't match the broadcast shape (1,3)

#Your answer goes here :

$w_{1,3}=  0.30345983 $ 

$w_{1,4}=  -0.50218887 $

$w_{2,3}= 0.80086496 $

$w_{2,4}= 0.19945278 $

$w_{6,3}= 0.20432479 $

$w_{6,4}= -0.40273608 $

$w_{3,5}= -0.62034179 $

$w_{4,5}= 0.38996086 $

$w_{7,5}= 0.47696756 $




<b>Part 2</b>: Neural Network Implementation

Please read all source files carefully and understand the data structures and all functions.
You are to complete the missing code. 
First you should define the neural network (using the NeuralNetwork class, see in the <a href="NeuralNetwork.py"> NeuralNetwork.py </a> file) and reinitialise weights. 
Then you will to complete the Feed Forward and the Back-propagation functions. 

<b>Question 1.2.1</b>: Define the neural network corresponding to the one in part 1

In [23]:
#create the network
my_nnet = nn.NNet(2,2,1,50,1)

In [25]:
#Data preparation 
X=[0.8,0.2]
Y=[0.4]
data=[]
data.append(X)
data.append(Y)

#initialize weights
wi=np.array([[0.3,-0.5],[0.8,0.2],[0.2,-0.4]])
wo=np.array([[-0.6],[0.4],[0.5]])
my_nnet.init_w(wi,wo)
print(my_nnet.Wi_h)
print(my_nnet.Wh_o)

[[ 0.3 -0.5]
 [ 0.8  0.2]
 [ 0.2 -0.4]]
[[-0.6]
 [ 0.4]
 [ 0.5]]


<b>Question 1.2.2</b>: Implement the Feed Forward function (feedForward(X) in the NeuralNetwork.py file)



Check your network outputs the expected value (the one you computed in question 1.1)

In [26]:
# test my  Feed Forward function 
Output_activation=my_nnet.feedForward(X)
print("output activation =%.3f" %(Output_activation))

output activation =0.526


<b>Question 1.2.3</b>: Implement the Back-propagation Algorithm (backPropagate(Y) in the NeuralNetwork.py file)  


In [27]:
def myBackPropagate(nn, targets):
    # Implement it in the NeuralNetwork.py file and when finalised copy and paste your FeedForward function here
    nn.dEdU2 = (nn.a_out-targets)*tf.dsigmoid(nn.a_out)
    # calculate error terms for hidden
    nn.dEdU1 = np.multiply(np.dot(nn.Wh_o,nn.dEdU2), tf.dsigmoid(nn.a_hidden))
    # update output weights
    nn.Wh_o = nn.Wh_o - nn.learning_rate*np.outer(nn.a_hidden,nn.dEdU2)
    # update input weights
    nn.Wi_h = nn.Wi_h - nn.learning_rate*np.outer(nn.a_input,nn.dEdU1[:-1])
    # calculate error
    E = (1.0/2.0)*((targets-nn.a_out)**2.0)


Check the gradient values and weight updates are correct (similar to the ones you computed in question 1.1)

In [28]:
#test Back-propagation function
my_nnet.init_w(wi,wo)
Output_activation=my_nnet.feedForward(X)
my_nnet.backPropagate(Y)
print('wi_new=', my_nnet.Wi_h)
print('wo_new=', my_nnet.Wh_o)


wi_new= [[ 0.30345983 -0.50218887]
 [ 0.80086496  0.19945278]
 [ 0.20432479 -0.40273608]]
wo_new= [[-0.62034179]
 [ 0.38996086]
 [ 0.47696756]]


In [59]:
#Print weights after backpropagation and comparing
print(w2)
print(my_nnet.Wh_o)
print(w1)
print(my_nnet.Wi_h)

[[-0.62034179  0.38996086  0.47696756]]
[[-0.62034179]
 [ 0.38996086]
 [ 0.47696756]]
[[ 0.30345983 -0.50218887]
 [ 0.80086496  0.19945278]
 [ 0.20432479 -0.40273608]]
[[ 0.30345983 -0.50218887]
 [ 0.80086496  0.19945278]
 [ 0.20432479 -0.40273608]]


Your Feed Forward and Back-Propagation implementations are working, Great!! Let's tackle a real world problem.

# Section 2 : The MNIST Challenge! 

<b>Data Preparation</b>

The MNIST dataset consists of handwritten digit images it contains 60,000 examples for the training set and 10,000 examples for testing. In this Lab Session, the official training set of 60,000 is divided into an actual training set of 50,000 examples, 10,000 validation examples and 10,000 examples for test. All digit images have been size-normalized and centered in a fixed size image of 28 x 28 pixels. The images are stored in byte form you will use the NumPy python library to read the data files into NumPy arrays that we will use to train the ANN.

The MNIST dataset is available in the Data folder.
To get the training, testing and validation data, run the the load_data() function.


In [ ]:
from Resources.utils import *
import gzip
import _pickle as cPickle
f = gzip.open('Resources/mnist.pkl.gz', 'rb')
train_set, valid_set, test_set = cPickle.load(f)
f.close()
#training_data, validation_data, test_data=load_data()







<b>MNIST Dataset Digits Visualisation</b>

In [ ]:
ROW = 2
COLUMN = 4
for i in range(ROW * COLUMN):
    # train[i][0] is i-th image data with size 28x28
    image = training_data[i][0].reshape(28, 28)   
    plt.subplot(ROW, COLUMN, i+1)          
    plt.imshow(image, cmap='gray')  # cmap='gray' is for black and white picture.
plt.axis('off')  # do not show axis value
plt.tight_layout()   # automatic padding between subplots
plt.show()



<b>Part 1</b>: Creating the Neural Networks

The input layer of the neural network contains neurons encoding the values of the input pixels. The training data for the network will consist of many 28 by 28 pixel images of scanned handwritten digits, and so the input layer contains 784=28×28 neurons. The second layer of the network is a hidden layer, we set the neuron number in the hidden layer to 30. The output layer contains 10 neurons. 

<b>Question 2.1.1</b>: Create the network described above using the NeuralNetwork class

In [ ]:
#create the network
from NeuralNetwork import * 
my_mnist_net = 




<b>Question 2.1.2</b>: Add the information about the performance of the neural network on the test set at each epoch

In [ ]:
test_accuracy=my_mnist_net.predict(test_data)/100
print('Test_Accuracy  %-2.2f' % test_accuracy)




<b>Question 2.1.3</b>: Train the Neural Network and comment your findings

In [ ]:
#train your network 
my_mnist_net.train(training_data,validation_data)

#save your model in Models/ using a distinguishing name for your model (architecture, learning rate, etc...)







#Note your observations here. 

<b>Question 2.1.4</b>: Guess digit, Implement and test a python function that predict the class of a digit (the folder images_test contains some examples of images of digits)


In [ ]:
#Your implementation goes here














<b>Part 2</b>: Change the neural network structure and parameters to optimize performance

<b> Question 2.2.1</b>: Change the learning rate (0.001, 0.1, 1.0 , 10). Train the new neural nets with the original specifications (Part 2.1), for 50 iterations. 
Plot test accuracy vs iteration for each learning rate on the same graph. Report the maximum
test accuracy achieved for each learning rate. Which one achieves the maximum test accuracy?

In [ ]:
#Your implementation with a learning rate of 0.001 goes here 
















In [ ]:
#Your implementation with a learning rate of 1.0 goes here 



















In [ ]:
#Your implementation with a learning rate of 10 goes here 





















#Your answer for Question 2.2.1 goes here

 <b> Question 2.2.2 : </b> initialize all weights to 0.  Plot the training accuracy curve.
Comment your results
    
        

In [ ]:
#Your implementation goes here

















#Your answer goes here

<b> Question 2.2.3 : </b> Try with a different transfer function (such as tanh).
 File transfer_functions.py provides you the python implementation of the tanh function and its derivative

In [ ]:
#Your implementation goes here

















#Your answer goes here


<b> Question 2.2.4 : </b>  Add more neurons in the hidden layer (try with 100, 200, 300). Plot the curve representing the validation accuracy versus the number of neurons in the hidden layer.  (Choose and justify other hyper-parameters)

In [ ]:
#Your implementation goes here
























#Your answer goes here

<b> Question 2.2.5 : </b> Add one additionnal hidden layers and train your network, discuss your results with different setting. 



In [ ]:
#Your implementation goes here

















#Your answer goes here